### ISSUE TITLE
wireguard plugin makes checkmk 2.0 "crash"

### ISSUE THREAD

**Issue by Timdebruijn** [HeinleinSupport/check_mk_extensions#76]
After updating checkmk to 2.0.0, the wireguard plugin is not working.

The crash report:

Exeption: 

> AttributeError ('dict' object has no attribute 'iteritems')

Traceback: 

> File "/omd/sites/timdebruijn/lib/python3/cmk/base/decorator.py", line 37, in wrapped_check_func
>     status, infotexts, long_infotexts, perfdata = check_func(hostname, *args, **kwargs)
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 778, in check_discovery
>     services, host_label_discovery_result = _get_host_services(
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1574, in _get_host_services
>     services, host_label_discovery_result = _get_node_services(
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1595, in _get_node_services
>     services, host_label_discovery_result = _get_discovered_services(
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1623, in _get_discovered_services
>     discovered_services, host_label_discovery_result = _discover_host_labels_and_services(
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1392, in _discover_host_labels_and_services
>     discovered_services = [] if discovery_parameters.only_host_labels else _discover_services(
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1444, in _discover_services
>     service_table.update({
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1444, in <dictcomp>
>     service_table.update({
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1512, in _execute_discovery
>     yield from _enriched_discovered_services(hostname, check_plugin.name, plugins_services)
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/discovery.py", line 1526, in _enriched_discovered_services
>     for service in plugins_services:
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/api/agent_based/register/check_plugins.py", line 72, in filtered_generator
>     for element in generator(*args, **kwargs):
>   File "/omd/sites/timdebruijn/lib/python3/cmk/base/api/agent_based/register/check_plugins_legacy.py", line 88, in discovery_migration_wrapper
>     for element in original_discovery_result:
>   File "/omd/sites/timdebruijn/local/share/check_mk/checks/wireguard", line 39, in inventory_wireguard
>     for interface, peers in parsed.iteritems():

Local Variables:

> {'parsed': {'wg0': {'REDACTED': {'allowed-ips': '192.168.100.101/32',
                                                                     'endpoint': 'REDACTED:55107',
                                                                     'latest-handshake': 1615306323,
                                                                     'persistent-keepalive': '25',
                                                                     'transfer-rx': 4140,
                                                                     'transfer-tx': 16832}}}}

I use the latest mkp version (0.6)

If additional information is needed, please let me know.

**Comment by gurubert** [comment]
There is a cmk2.0 branch in the repo.
